### ISSUE TITLE
@babel/parser @babel/traverse cannot  use in browser

### ISSUE THREAD

**Issue by RGBWang** [luminaxster/syntax-highlighter#14]
@babel/parser @babel/traverse cannot  use in browser。
babel in browser lib is  @babel/standalone。
but cannot find  parser or traverse  in @babel/standalone,
how can I do it?

**Comment by luminaxster** [comment]
are you using npm? or using cdn for the files? Your bundled app should have code like [this](https://babel.dev/docs/en/babel-traverse).
