### ISSUE TITLE
Request | Support TSX format highlighting

### ISSUE THREAD

**Issue by HaimCandiTech** [luminaxster/syntax-highlighter#22]
Right now the library doesn't work well if there is any type in the code.

An easy way to fix it is by adjusting makeBabelParse - 

```
export const makeBabelParse = (parse, enableTsxHighlight) => {
   return (code, options = {}) => {
      return parse(
         code,
         {
            ...options,
            sourceType: "module",
            plugins: ["jsx", ...(enableTsxHighlight ? ['typescript'] : [])],
            errorRecovery: true
         });
      
   };
};
```

I could create a PR but I can't open branches for this repo :( 

Please address it so I will be able to use your library and not a forked copy

**Comment by luminaxster** [comment]
=) , I will handle with #23
