### ISSUE TITLE
Bug | Highlighting might not clear after disposal

### ISSUE THREAD

**Issue by HaimCandiTech** [luminaxster/syntax-highlighter#23]
In rare cases where there was a change in monaco's content after disposal of `highlightOnDidChangeModelContent`
The highlight might stay there

Steps to reproduce:
1. Set up monaco with JSX highlight library
2. Register to highlightOnDidChangeModelContent
3. Update monaco value (change from `<></>` to `<div></div>`
4. Immediately call  highlightOnDidChangeModelContent's dispose function

Expected Result:
No highlight

Result:
Incorrect highlight will be shown for the name of the JSX element

How to fix:
Add `clearTimeout(tid);` as the first line of:
https://github.com/luminaxster/syntax-highlighter/blob/28984b65e03351099e01d583d3bf7a17cf136620/src/core/MonacoJSXHighlighter.js#L230-L242

**Comment by luminaxster** [comment]
Thank you so much, I will fix this and #22  next weekend.
