### ISSUE TITLE
Highlight dissapears in multi model Editors

### ISSUE THREAD

**Issue by anubra266** [luminaxster/syntax-highlighter#6]
My editor hosts multiple models, Once I navigate to a different model, the highlighting disappears.

![Peek 2021-03-15 11-49](https://user-images.githubusercontent.com/30869823/111227774-5bd9c180-85e3-11eb-98f5-f5822888d259.gif)

**Comment by luminaxster** [comment]
Out of curiosity, what was it?

**Comment by anubra266** [comment]
@luminaxster I had to detect whenever my model changed, and reHighlight the code.
```js
function handleEditorDidMount(editor: any, monaco: any) {
    editor.onDidChangeModel(() => {
             monacoJSXHighlighter?.highlightCode();
     });
}
 
```
I suggest you add this to the package. To save others time, cause I doubt many people use monaco with just one model.

**Comment by luminaxster** [comment]
I wi
