### ISSUE TITLE
Usage with Next.js and monaco-editor/react

### ISSUE THREAD

**Issue by Magnuscake** [luminaxster/syntax-highlighter#7]
I've referred to [this issue](https://github.com/luminaxster/syntax-highlighter/issues/5), but I think my use case is a bit different. The issue is almost similar, where Next.js returns a `document not found error`. I wasn't able to reproduce it with codesandbox.io due to Next.js server limitations, so I've pasted the code below. Would really appreciate it if your help me out here.

```javascript
import { useRef } from "react";
import MonacoEditor, { EditorDidMount } from "@monaco-editor/react";
import prettier from "prettier";
import parser from "prettier/parser-babel";
import { parse } from "@babel/parser";
import traverse from "@babel/traverse";
import MonacoJSXHighlighter from "monaco-jsx-highlighter";

interface CodeEditorProps {
  initialValue: string;
  onChange(value: string): void;
}

const CodeEditor: React.FC<CodeEditorProps> = ({ initialValue, onChange }) => {
  const editorRef = useRef<any>();

  const onEditorDidMount: EditorDidMount = (getValue, monacoEditor) => {
    editorRef.current = monacoEditor;
    monacoEditor.onDidChangeModelContent(() => {
      onChange(getValue());
    });

    const babelParse = (code: string) =>
      parse(code, {
        sourceType: "module",
        plugins: ["jsx"],
      });

    const highlighter = new MonacoJSXHighlighter(
      // @ts-ignore
      window.monaco,
      babelParse,
      traverse,
      monacoEditor
    );
    // Activate highlighting (debounceTime default: 100ms)
    highlighter.highLightOnDidChangeModelContent();
    // Activate JSX commenting
    highlighter.addJSXCommentCommand();
  };

  // format with prettier
  const onFormatClick = () => {
    // get current value from editor
    const unformatted = editorRef.current.getModel().getValue();
    // format the value
    const formatted = prettier
      .format(unformatted, {
        parser: "babel",
        plugins: [parser],
        useTabs: false,
        semi: true,
        singleQuote: true,
        trailingComma: "es5",
      })
      .replace(/\n$/, "");
    // set the formatted value back in the editor
    editorRef.current.setValue(formatted);
  };

  return (
    <div className="editor-wrapper">
      <button
        className="button button-format is-primary is-small"
        onClick={onFormatClick}
      >
        Format
      </button>
      <MonacoEditor
        editorDidMount={onEditorDidMount}
        value={initialValue}
        language="javascript"
        theme="dark"
        height="500px"
        options={{
          wordWrap: "on",
          minimap: { enabled: false },
          showUnused: false,
          folding: false,
          lineNumbersMinChars: 3,
          fontSize: 16,
        }}
      />
    </div>
  );
};

export default CodeEditor;
```

**Comment by sidwebworks** [comment]
@Magnuscake I have been working on almost the same stack, trying to integrate this package inside my editor too. btw I think the first argument of onMount function is editor instance and second one is monaco instance, NOT `getState` please cross check, u don't need to take the instance from window just pass monaco directly

btw here is my repo https://github.com/sidwebworks/web-pen/

**Comment by sidwebworks** [comment]
Got it working, but @luminaxster  why is it polluting the console? 
![image](https://user-images.githubusercontent.com/58144379/143024614-dca3e2d7-32cc-4eac-9845-2e26f726b641.png)

**Comment by luminaxster** [comment]
Hi @sidwebworks! Could you share your fix? I noticed you went the web worker way, nice! I use babel's AST to highlight but also to transform the code in my project. I will change the default behavior to not log errors, thanks for the feeback!

**Comment by sidwebworks** [comment]
Hi, 
Sure actually the fix wasn't complicated at all. All I had to do is to use the `onMount` callback to setup the highlighter like this
```ts
import {parse} from "@babel/parser";
import traverse from "@babel/traverse";
import MonacoJSXHighlighter from 'monaco-jsx-highlighter';


const babelParse = code => parse(code, {
   sourceType: "module",
   plugins: ["jsx"]
});

export const initHandler: OnMount = (editor, monaco) => {
	
const monacoJSXHighlighter = new MonacoJSXHighlighter(
   monaco, babelParse, traverse, editor
);

monacoJSXHighlighter.highlightOnDidChangeModelContent(100);

monacoJSXHighlighter.addJSXCommentCommand();

};

```

**Comment by sidwebworks** [comment]
although I ended up with the custom approach cause I couldn't figure out exactly how to decouple the highlighting and comments logic from the package itself. Though I really liked the package, thanks for making this. I would be super interested if you can give like a overview of how exactly does package work? so maybe I can try to make something which uses ESBUILD or something like acorn and can be decoupled and used inside a web worker? 
Thanks

**Comment by luminaxster** [comment]
I'm rewriting the code to make the two features have a clear cut while reviewing it. thank you for your time and feedback =). The next update will have more info about the inner workings.

**Comment by luminaxster** [comment]
I wanted to use Monaco's web worker API, they mentioned exposing the AST was in the works, haven't checked lately. The fixes and the decoupled are up =).
