### ISSUE TITLE
incorrect highlight 

### ISSUE THREAD

**Issue by aboveyunhai** [luminaxster/syntax-highlighter#8]
![image](https://user-images.githubusercontent.com/35160613/145346618-c315d0eb-43b2-4588-bd91-b0f23cdace1a.png)
Direct modification from demo. 

The highlight is correct at the first render, but after I start to type, the highlighter seems to lose its integrity.

**Comment by aboveyunhai** [comment]
> ![image](https://user-images.githubusercontent.com/35160613/145346618-c315d0eb-43b2-4588-bd91-b0f23cdace1a.png) Direct modification from demo.
> 
> @luminaxster  The highlight is correct at the first render, but after I start to type, the highlighter seems to lose its integrity.

**Comment by aboveyunhai** [comment]
@luminaxster I tried to look through the source code but failed to understand how parsing works internally.
I also check how codesandbox highlighter works https://github.com/codesandbox/codesandbox-client/blob/196301c919dd032dccc08cbeb48cf8722eadd36b/packages/app/src/app/components/CodeEditor/Monaco/workers/syntax-highlighter.js
Just leave the link here in case if ppl can found the difference that covers the issue.

**Comment by luminaxster** [comment]
Thank you for letting me @aboveyunhai! It is a defect with the model change detection so it refreshes the highlighting, I'm looking into it and coming back with a fix shortly.

**Comment by luminaxster** [comment]
Coming back from vacation, looking into it tomorrow.
